title: Evan Morikawa
email: evan@evanmorikawa.com
description: The homepage for Evan Morikawa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evanmorikawa.com" # the base hostname & protocol for your site
twitter_username: e0m
github_username:  emorikawa

# Build settings
markdown: kramdown
